---



- hosts: all



  tasks:

  - name: installig www server apache

    yum:

      name: httpd

      update_cache: yes





  - name: restart apache

    service:

      name: httpd

      state: restarted



  - copy:

      content: "baca"

      dest: "/var/www/html/1.txt"
